openapi: 3.0.0
info:
  title: Backend API with SQLite
  description: A sample API that uses a SQLite database as backend
  version: 1.0.0

servers:
  - url: https://bes6a-bpgkabg9hugfb2eg.eastus2-01.azurewebsites.net/api
    description: Local development server

paths:
  /users:
    get:
      summary: Returns all users
      responses:
        '200':
          description: A JSON array of user objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Created

  /users/{id}:
    get:
      summary: Returns a user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    put:
      summary: Updates a user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: OK
        '404':
          description: User not found
    delete:
      summary: Deletes a user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '404':
          description: User not found

  /products:
    get:
      summary: Returns all products
      responses:
        '200':
          description: A JSON array of product objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Creates a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Created

  /products/{id}:
    get:
      summary: Returns a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    put:
      summary: Updates a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: OK
        '404':
          description: Product not found
    delete:
      summary: Deletes a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '404':
          description: Product not found

  /orders:
    get:
      summary: Returns all orders
      responses:
        '200':
          description: A JSON array of order objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Creates a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderInput'
      responses:
        '201':
          description: Created

  /orders/{id}:
    get:
      summary: Returns an order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: An order object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
    put:
      summary: Updates an order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderInput'
      responses:
        '200':
          description: OK
        '404':
          description: Order not found
    delete:
      summary: Deletes an order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '404':
          description: Order not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
    
    UserInput:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        created_at:
          type: string
          format: date-time
    
    ProductInput:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
    
    Order:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        total_amount:
          type: number
        status:
          type: string
        created_at:
          type: string
          format: date-time
    
    OrderInput:
      type: object
      required:
        - user_id
        - total_amount
      properties:
        user_id:
          type: integer
        total_amount:
          type: number
        status:
          type: string
      summary: Remover aposta
      parameters:
        - $ref: '#/components/parameters/idPath'
      responses:
        '204':
          description: Removido com sucesso
        '404': { $ref: '#/components/responses/NotFound' }

  /resultados:
    get:
      tags: [Resultados]
      summary: Listar resultados de jogos
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - name: idJogo
          in: query
          schema: { type: integer, format: int32 }
      responses:
        '200':
          description: Lista de resultados
          headers:
            X-Total-Count:
              description: Total de registros no backend
              schema: { type: integer, format: int64 }
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Resultado' }
    post:
      tags: [Resultados]
      summary: Registrar resultado de jogo
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ResultadoCreate' }
      responses:
        '201':
          description: Resultado criado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Resultado' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '404': { $ref: '#/components/responses/NotFound' }

  /resultados/{id}:
    get:
      tags: [Resultados]
      summary: Obter resultado por ID
      parameters:
        - $ref: '#/components/parameters/idPath'
      responses:
        '200':
          description: Resultado encontrado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Resultado' }
        '404': { $ref: '#/components/responses/NotFound' }
    put:
      tags: [Resultados]
      summary: Atualizar resultado (substituição)
      parameters:
        - $ref: '#/components/parameters/idPath'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ResultadoUpdate' }
      responses:
        '200':
          description: Resultado atualizado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Resultado' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '404': { $ref: '#/components/responses/NotFound' }
    patch:
      tags: [Resultados]
      summary: Atualização parcial do resultado
      parameters:
        - $ref: '#/components/parameters/idPath'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ResultadoPatch' }
      responses:
        '200':
          description: Resultado atualizado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Resultado' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '404': { $ref: '#/components/responses/NotFound' }
    delete:
      tags: [Resultados]
      summary: Remover resultado
      parameters:
        - $ref: '#/components/parameters/idPath'
      responses:
        '204':
          description: Removido com sucesso
        '404': { $ref: '#/components/responses/NotFound' }

components:
  parameters:
    idPath:
      name: id
      in: path
      required: true
      description: Identificador numérico do recurso
      schema: { type: integer, format: int32 }
    page:
      name: page
      in: query
      description: Página (base 1)
      schema:
        type: integer
        minimum: 1
        default: 1
    pageSize:
      name: pageSize
      in: query
      description: Tamanho da página
      schema:
        type: integer
        minimum: 1
        maximum: 200
        default: 20

  responses:
    BadRequest:
      description: Requisição inválida
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ApiError' }
    NotFound:
      description: Recurso não encontrado
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ApiError' }
    Conflict:
      description: Conflito de integridade (ex e-mail duplicado)
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ApiError' }

  schemas:
    # ---------- USUARIOS ----------
    Usuario:
      type: object
      description: Representa o jogador/usuário do sistema
      properties:
        id:
          type: integer
          format: int32
          description: Identificador único do usuário
          example: 1001
        nome:
          type: string
          description: Nome completo
          example: "Ana Silva"
        email:
          type: string
          format: email
          description: E-mail único para login/contato
          example: "ana.silva@example.com"
        saldo:
          type: number
          format: double
          description: Saldo disponível para apostas
          example: 250.75
        criadoEm:
          type: string
          format: date-time
          description: Data/hora de criação do cadastro
        atualizadoEm:
          type: string
          format: date-time
          description: Data/hora da última atualização
      required: [id, nome, email, saldo, criadoEm]
    UsuarioCreate:
      allOf:
        - type: object
          properties:
            nome: { type: string }
            email: { type: string, format: email }
            saldo:
              type: number
              format: double
              default: 0.0
          required: [nome, email]
    UsuarioUpdate:
      allOf:
        - $ref: '#/components/schemas/UsuarioCreate'
    UsuarioPatch:
      type: object
      additionalProperties: false
      properties:
        nome: { type: string }
        email: { type: string, format: email }
        saldo: { type: number, format: double }

    # ---------- JOGOS ----------
    JogoStatus:
      type: string
      description: Status do jogo
      enum: [aberto, fechado, processado]
      example: aberto
    Jogo:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 501
        dataHora:
          type: string
          format: date-time
          description: Data/hora da rodada
        status:
          $ref: '#/components/schemas/JogoStatus'
      required: [id, dataHora, status]
    JogoCreate:
      type: object
      properties:
        dataHora:
          type: string
          format: date-time
          description: Se omitido, o backend define a hora atual
        status:
          $ref: '#/components/schemas/JogoStatus'
      required: [status]
    JogoUpdate:
      allOf:
        - $ref: '#/components/schemas/JogoCreate'
    JogoPatch:
      type: object
      additionalProperties: false
      properties:
        dataHora: { type: string, format: date-time }
        status: { $ref: '#/components/schemas/JogoStatus' }

    # ---------- APOSTAS ----------
    Aposta:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 9001
        idUsuario:
          type: integer
          format: int32
          description: Referência ao usuário que apostou
          example: 1001
        idJogo:
          type: integer
          format: int32
          description: Referência ao jogo (rodada)
          example: 501
        valor:
          type: number
          format: double
          description: Valor apostado
          example: 5.0
        escolha:
          type: string
          description: Escolha realizada (ex. linha/jogada/slot)
          example: "linha-1"
        criadoEm:
          type: string
          format: date-time
      required: [id, idUsuario, idJogo, valor, escolha, criadoEm]
    ApostaCreate:
      type: object
      properties:
        idUsuario:
          type: integer
          format: int32
        idJogo:
          type: integer
          format: int32
        valor:
          type: number
          format: double
          minimum: 0.01
        escolha:
          type: string
      required: [idUsuario, idJogo, valor, escolha]
    ApostaUpdate:
      allOf:
        - $ref: '#/components/schemas/ApostaCreate'
    ApostaPatch:
      type: object
      additionalProperties: false
      properties:
        idUsuario: { type: integer, format: int32 }
        idJogo: { type: integer, format: int32 }
        valor: { type: number, format: double, minimum: 0.01 }
        escolha: { type: string }

    # ---------- RESULTADOS ----------
    Resultado:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 3001
        idJogo:
          type: integer
          format: int32
          description: Referência ao jogo
          example: 501
        combinacao:
          type: string
          description: Combinação sorteada (ex. "A-A-B")
          example: "tigre-tigre-tigre"
        ganhou:
          type: boolean
          description: Indica se houve ganhador (para a rodada como um todo ou regra do sistema)
          example: true
        premio:
          type: number
          format: double
          description: Valor total de prêmio distribuído
          example: 100.0
        processadoEm:
          type: string
          format: date-time
      required: [id, idJogo, combinacao, ganhou, premio]
    ResultadoCreate:
      type: object
      properties:
        idJogo: { type: integer, format: int32 }
        combinacao: { type: string }
        ganhou: { type: boolean }
        premio:
          type: number
          format: double
          minimum: 0
      required: [idJogo, combinacao, ganhou, premio]
    ResultadoUpdate:
      allOf:
        - $ref: '#/components/schemas/ResultadoCreate'
    ResultadoPatch:
      type: object
      additionalProperties: false
      properties:
        idJogo: { type: integer, format: int32 }
        combinacao: { type: string }
        ganhou: { type: boolean }
        premio: { type: number, format: double, minimum: 0 }

    # ---------- ERROS ----------
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: Código de erro semântico
          example: VALIDATION_ERROR
        message:
          type: string
          description: Mensagem explicativa
          example: "Campo 'email' é obrigatório."
        details:
          type: object
          additionalProperties: true
      required: [code, message]
