name: Trigger auto deployment for bes6ateste

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bes6ateste-AutoDeployTrigger-8ec3a63a-7b0c-43ef-b5ca-d57dfa6f469e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BES6ATESTE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BES6ATESTE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BES6ATESTE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.BES6ATESTE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BES6ATESTE_REGISTRY_PASSWORD }}
          containerAppName: bes6ateste
          resourceGroup: DefaultResourceGroup-WUS2
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


